config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :users, only: %i[show new create]
  resources :feeds, only: %i[index new edit create update destroy] do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: %i[index create destroy]
  resources :sessions, only: %i[new create destroy]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :feed

  validates :feed_id, uniqueness: { scope: [:user_id] }
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user

  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feeds
  has_many :favorites, dependent: :destroy
  has_many :favorite_feeds, through: :favorites, source: :feed

  has_secure_password
  validates :password_digest, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include FeedsHelper

  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_logged_in

  def index
    @favorites = current_user.favorites
                             .includes(:feed)
                             .order('favorites.created_at')
  end

  def create
    notice =
      if current_user.favorites.create(feed_id: params[:feed_id])
        'お気に入り登録しました'
      else
        'すでにお気に入りのフィードです'
      end
    redirect_to favorites_path, notice: notice
  end

  def destroy
    current_user.favorites.find_by_id(params[:id])&.destroy
    redirect_to feeds_path
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :require_logged_in, except: %i[index]
  before_action :set_current_user_feed, only: %i[edit update destroy]

  def index
    @feeds = Feed.all.order('created_at desc')
    @favorite_feeds = current_user&.favorite_feeds
  end

  def new
    @feed =
      if params[:back]
        current_user.feeds.build(feed_params)
      else
        current_user.feeds.build
      end
  end

  def edit
  end

  def create
    @feed = current_user.feeds.create!(feed_params)
    FeedMailer.feed_mail(@feed).deliver
    redirect_to feeds_path
  end

  def update
    if @feed.update(feed_params)
      redirect_to feeds_path
    else
      render :edit
    end
  end

  def destroy
    @feed.delete
    redirect_to feeds_path
  end

  def confirm
    @feed = current_user.feeds.build(feed_params)
    render :new and return if @feed.invalid?
  end

  private

  def feed_params
    params.require(:feed).permit(:description, :image, :image_cache, :user_id)
  end

  def set_current_user_feed
    @feed = current_user.feeds.find_by_id(params[:id])
    redirect_to feeds_path unless @feed
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_in, except: %i[new create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in(user.id)
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'Eメールアドレスかパスワードが不正です'
      render :new
    end
  end

  def destroy
    log_out
    flash.now[:danger] = 'ログアウトしました'
    redirect_to new_session_path
  end

  private

  def session_params
    params.require(:session)
          .permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_logged_in, except: %i[new create]

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user.id)
      redirect_to user_path(current_user.id), notice: 'あなたのアカウントを作成しました'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def form_submit_path
    case action_name
    when 'new', 'confirm'
      confirm_feeds_path
    when 'edit', 'update', 'create'
      feed_path(@feed)
    else
      raise "called by unexpected controller #{action_name}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user_id)
    session[:user_id] = user_id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user_id)
    current_user && current_user.id == user_id
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
  end

  # TODO: move to suite place
  def require_logged_in
    redirect_to new_session_path, notice: 'ログインしてください' unless logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.haml
%h1.title お気に入りフィード一覧
- @favorites.each do |fav|
  %article.media
    .media-content
      .content
        %p= fav.feed.description
        %p= image_tag fav.feed.image
        %small #{fav.feed.created_at}に#{fav.feed.user.name}さんが投稿
        %nav.level.is-mobile
          .level-left
            .level-item
              = link_to 'お気に入り解除', favorite_path(fav), method: :delete, class: 'button'
            - if current_user?(fav.user)
              %span.tag.is-light あなたのフィード
          .level-right
            - if current_user?(fav.user)
              .level-item
                = link_to '削除', feed_path(fav.feed), method: :delete, data: { confirm: '本当に削除していいですか?' }
              .level-item
                = link_to '編集', edit_feed_path(fav.feed)

app/views/feeds/_form.html.haml
= form_with model: feed, url: form_submit_path, local: true do |f|
  - if feed.errors.any?
    .notification.is-warning
      %h2 #{pluralize(feed.errors.count, 'error')} prohibited this feed from being saved:
      %ul
        - feed.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :description
    .control= f.text_field :description
  .field
    = f.label :image
    .control
      = f.file_field :image
  .field
    .control
      = f.submit '投稿'

app/views/feeds/confirm.html.haml
%h1.title 投稿内容確認
%p 以下の内容で、送信します。
%section.section
  = form_with(model: @feed, url: feeds_path, local: true) do |form|
    = form.hidden_field :description
    %p.content= @feed.description
    = image_tag(@feed.image)
    = form.hidden_field :image_cache
    = form.hidden_field :user_id
    .field
      .control
        = form.submit '投稿する', class: 'button'
  = form_with(model: @feed, url: new_feed_path, local: true, method: :get) do |form|
    = form.hidden_field :description
    = form.hidden_field :image
    = form.hidden_field :user_id
    .field
      .control
        = form.submit 'もどる', name: 'back', class: 'button'

app/views/feeds/edit.html.haml
%h1 Editing feed
= render partial: 'form', locals: { feed: @feed }
= link_to 'もどる', feeds_path

app/views/feeds/index.html.haml
%h1.title フィード一覧
- @feeds.each do |feed|
  %article.media
    .media-content
      .content
        %p= feed.description
        %p= image_tag feed.image
        %small #{feed.created_at}に#{feed.user.name}さんが投稿
        - if logged_in?
          - if current_user?(feed.user_id)
            %nav.level.is-mobile
              .level-left
                %span.tag.is-light あなたのフィード
              .level-right
                .level-item
                  = link_to '削除', feed_path(feed.id), method: :delete, data: { confirm: '本当に削除していいですか?' }
                .level-item
                  = link_to '編集', edit_feed_path(feed.id)
          - else
            %nav.level.is-mobile
              .level-right
                .level-item
                  - if @favorite_feeds.include?(feed)
                    %span.tag.is-primary あなたのお気に入り
                  - else
                    = link_to 'お気に入りにする', favorites_path(feed_id: feed.id), method: :post, class: 'button'

app/views/feeds/new.html.haml
%h1.title  フィード投稿
= render partial: 'form', locals: { feed: @feed }
= link_to '戻る', feeds_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title= content_for?(:title) ? yield(:title) : 'Instagram Clone'
    = csrf_meta_tags
    %meta{ charset: 'utf-8' }/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }/
  %body
    %nav.navbar.is_mobile
      .navbar-brand= link_to 'Instagram Clone', '#', class: 'navbar-item is-size-4 has-text-weight-bold	'
      .navbar-menu.is-active.is-mobile
        .navbar-start
          .navbar-item= link_to 'フィード一覧', feeds_path, class: 'navbar-item'
          - if logged_in?
            .navbar-item= link_to 'お気に入りフィード一覧', favorites_path, class: 'navbar-item'
            .navbar-item= link_to '投稿する', new_feed_path, class: 'navbar-item'
        .navbar-end
          - if logged_in?
            .navbar-item= link_to current_user.name, user_path(current_user.id), class: 'navbar-item'
            .navbar-item
              .buttons= link_to 'ログアウト', session_path(current_user.id), method: :delete, class: 'button is-light'
          - else
            .navbar-item
              .buttons= link_to 'ユーザー登録', new_user_path, class: 'navbar-item button is-dark'
            .navbar-item
              .buttons= link_to 'ログイン', new_session_path, class: 'navbar-item button is-light'
    - flash.each do |key, value|
      .notification.is-info= content_tag(:div, value, class: key.to_s)
    %section.section
      .container
        = yield

app/views/users/new.html.haml
- content_for(:title) { 'ユーザ登録' }
%h1.title ユーザ登録
- if @user.errors.any?
  .notification.is-warning
    %h2
      = pluralize(@user.errors.count, 'error')
      prohibited this @user from being saved:
    %ul
      - @user.errors.full_messages.each do |message|
        %li= message
= form_with(model: @user, local: true) do |f|
  .field
    = f.label :name, class: 'label'
    .control
      = f.text_field :name, class: 'form-control', placeholder: 'FIRSTNAME, lastname'
  .field
    = f.label :email, class: 'label'
    .control
      = f.email_field :email, class: 'form-control', placeholder: 'name@example.com'
  .field
    = f.label :password, class: 'label'
    .control
      = f.password_field :password, class: 'form-control', placeholder: 'must be longer than 6 charactors'
  .field
    = f.label :password_confirmation, class: 'label'
    .control
      = f.password_field :password_confirmation, class: 'form-control', placeholder: 'pleas duplicate the password'
  .field
    .control
      = f.submit '登録', class: 'button'

app/views/users/show.html.haml
- content_for(:title) { "#{@user.name}さんのページ" }
%h1.title
  = @user.name
  さんのページ
.columns
  .card
    .card-content
      %p.title.is-4 メールアドレス
      %p.content= @user.email